# -*- coding: utf-8 -*-
#!C:/Users/arif/AppData/Local/Programs/Python/Python35-32/python.exe
# Generated by Django 1.10.6 on 2017-03-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(upload_to='static/images/projects/', verbose_name='Изображение (500х500)'),
        ),
    ]
